theme: jekyll-theme-minimal
title: Mohamed Kabbaj
description: Data Scientist & MLOps Engineer | MS à Télécom Paris | 6 ans d'expérience en IA, Machine Learning et Statistiques
logo: https://avatars.githubusercontent.com/u/kabbstat
show_downloads: false
lang: fr